name: Test

on:
  workflow_dispatch:

jobs: 
  test: 
    runs-on: ubuntu-latest
    environment:
      name: devs
    steps:
      - name: prueba¡
        run: echo "run prueba ${{ vars.ENTORNO }}"