name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - devs
  pull_request:
      branches:
        - prod
jobs:
  example-job:
    runs-on: ubuntu-latest
        
    steps:
    - name: Imprimir nombre de la rama
      run: |
        echo "Nombre de la rama: $GITHUB_REF"
        echo "::set-env name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        
    - name: Configurar variable de entorno
      run: |
       echo "Usando el nombre de la rama en otro paso: $BRANCH_NAME"
        
    - name: Otro paso que usa el nombre de la rama
      run: |
        echo "Usando el nombre de la rama en otro paso: $BRANCH_NAME"


#jobs: 
#  build:
#    runs-on: ubuntu-latest
#    environment:#
#      name: ${{ github.ref }}
#    steps:
#     -
#        name: Checkout
#        uses: actions/checkout@v4
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - 
#        name: Build and push
#        uses: docker/build-push-action@v5
#        env: 
#          ENTORNO_GIT: ${{ vars.ENTORNO }}
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.ENTORNO }}:latest
#          build-args: ENTORNO_GIT=${{ vars.ENTORNO }}"""

