name: Test

on:
  workflow_dispatch:
  push:
    branches:
    - devs
  pull_request:
      branches:
        - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: rama
      run: |
        branch_name=$(basename $GITHUB_REF)
        echo "Nombre de la rama: $branch_name"


#jobs: 
#  build:
#    runs-on: ubuntu-latest
#    environment:#
#      name: ${{ github.ref }}
#    steps:
#     -
#        name: Checkout
#        uses: actions/checkout@v4
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - 
#        name: Build and push
#        uses: docker/build-push-action@v5
#        env: 
#          ENTORNO_GIT: ${{ vars.ENTORNO }}
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.ENTORNO }}:latest
#          build-args: ENTORNO_GIT=${{ vars.ENTORNO }}"""

